### ISSUE TITLE
DynamicMultiByteUnsignedInteger.fromMultiByte bug/weirdness 

### ISSUE THREAD

**Issue by IlyaGazman** [hhu-bsinfo/dxram#14]
Looks like you got a bug or some weird code in `DynamicMultiByteUnsignedInteger` in the below method. The `pos` is never changed, the `while` condition is always true. And I think that the `if` condition is always true as well because I don't see how the operation of `x & 0x80` will result in a value equal to 1

```
public static long fromMultiByte(final byte[] p_array, final int p_arrayOffset) {
        int pos = 0;
        long ret = 0;
        
        while (pos < 9) {
            ret |= (long) (p_array[p_arrayOffset + pos] & 0x7F) << 7 * pos;
            if ((p_array[p_arrayOffset + pos] & 0x80) != 1) {
                break;
            }
        }

        return ret;
    }
```

**Comment by stnot** [comment]
That part doesn't look correct indeed. However, I can't remember the last time we have used the class DynamicMultiByteUnsignedInteger and it is actually code that isn't used anymore on the master branch. The next version is currently in development (see branch development). There, we have already removed the class as it is no longer needed (we did some housekeeping which was definitely necessary).
Still, thank you for contributing by pointing this out.
